### PR TITLE
Function*.parameterType*() tests added #477

### PR DESCRIPTION
**Pull request by ruslansennov**

### CODE REVIEW

**Comment by ruslansennov** [comment]
No events from travis up to now (15 minutes). I believe it must be started manually

**Comment by danieldietrich** [comment]
There is no PR build slot. I will merge it to see a new build.

**Comment by ruslansennov** [comment]
+1% :)

**Comment by danieldietrich** [comment]
Generator stuff has always a weight factor > 1 :)

**Pull request merged**
