### PR TITLE
Futures

### PR DESCRIPTION
**Pull request by DillonJettCallis**
Created Scala-like Futures and Promises. Some semantic issues may remain.

### CODE REVIEW

**Comment by danieldietrich** [comment]
This is great, many thanks!

The method `nil()` called within Future changed to `empty()`. I think this is the reason why the ci build fails.

Please do the following:

```java
git remote -v
git remote add upstream https://github.com/javaslang/javaslang.git
git remote -v
git fetch upstream
git checkout futures
git merge upstream/master
```

to merge the actual Javaslang master into your project. When in doubt with errors or new API let me know. We can fix the stuff - just commit the merged stuff to get travis-ci feedback on success or errors.

Thanks!

Daniel

**Comment by danieldietrich** [comment]
Sorry, don't know why I didn't merged it - thought that the build failed.

Great work!!

**Comment by danieldietrich** [comment]
Hi @DillonJettCallis,

do you mind if I remove the `@author` tags from javadoc? There are no other `@author` tags in the project and I want to keep it consistent.

Also it is redundant to the git repo history, where all contributors are mentioned.

Instead I plan to create some sort of 'hall of fame' on the homepage, where people like you and @ruslansennov are explicitly mentioned in conjunction with their efforts (Futures, Collections, etc.).

Deal?

**Comment by DillonJettCallis** [comment]
Yes of course. I don't mind, I was just copying patterns seen elsewhere.

**Comment by danieldietrich** [comment]
Great!

The hall of fame will be cool. I'm currently re-designing the page :-)

**Pull request merged**
