### PR TITLE
Implement extended Multimap filters

### LINKED ISSUE #1401: Add new Map methods
What you think about this methods in `Map` interface?
* `filter(BiPredicate<K, V>)`
* `filterKeys(Predicate<K>)`
* `filterValues(Predicate<V>)`
* `removeAll(BiPredicate<K, V>)`
* `removeKeys(Predicate<K>)` / `removeAllKeys(Predicate<K>)`
* `removeValues(Predicate<V>)` / `removeAllValues(Predicate<V>)`

### PR DESCRIPTION
**Pull request by valery1707**
Fix #1401

### CODE REVIEW

**Comment by valery1707** [comment]
Strange. Where `codecov` and `Travis-CI`?

**Comment by valery1707** [comment]
How can I force `Travis-CI` to build this PR?
@danieldietrich , @ruslansennov

**Comment by ruslansennov** [comment]
Sometimes it happens...
I don't know what to do in this case

**Comment by valery1707** [comment]
@ruslansennov, may be I need to close this PR and open new?

**Comment by ruslansennov** [comment]
it makes sense

**Pull request closed without merging**
