### PR TITLE
Adding Convertible.toLeft(R right) and Convertible.toRight(L left)

### PR DESCRIPTION
**Pull request by enelson**
Code for issue #969.

### CODE REVIEW

**Comment by ruslansennov** [comment]
Could you add tests?

**Comment by enelson** [comment]
@ruslansennov certainly. I didn't see any tests for the existing Supplier versions, so I'll add those too.

**Comment by enelson** [comment]
@ruslansennov and @danieldietrich, I added these tests to `AbstractTraversableTest`, but wondering if I should move those into `AbstractValueTest`?

**Comment by ruslansennov** [comment]
I would add to <code>AbstractValueTest</code>

**Comment by enelson** [comment]
@ruslansennov I agree, didn't feel right where I put it. Committing changes soon.

**Comment by danieldietrich** [comment]
Great, and also thank you for adding the missing tests!

**Pull request merged**
