### PR TITLE
Update default `Idea` settings

### PR DESCRIPTION
**Pull request by paplorinc**
* align multiline ternaries
* align chained methods
* collapse double empty lines
* force braces for `if`/`while`/`for`
* add `final` to local variables

javaslang_xml
---
default_xml
---
newfile

### CODE REVIEW

**Comment by danieldietrich** [comment]
Thx! Just to get sure - did you export it like described in `.ide/README.md`?

```
IntelliJ IDEA
-------------

The following IntelliJ IDEA settings are exported (File/Export Setting):

* Code Style
* File templates
* Inspection profiles

See also [issue #133](https://github.com/javaslang/javaslang/issues/133)).
```

Another question: Do the 'File and code templates' on your machine contain the Javaslang file header (ascii art)? It once worked for me but after installing another IntelliJ version and importing the Javaslang settings, the custom file templates disappeared.

**Comment by paplorinc** [comment]
> Just to get sure - did you export it like described in .ide/README.md?

Yes, but feel free to check out either the screenshots containing the diffs, or locally the two jars.

> Do the 'File and code templates' on your machine contain the Javaslang file header (ascii art)?

yes, attached a screenshot for that also (i.e. imported the settings and created a new file)

**Comment by danieldietrich** [comment]
Sounds good - I will merge and import your settings...

**Comment by danieldietrich** [comment]
Hi @paplorinc ,

the alignment of chained methods looks ... eh ... really awful. It is too much waste of space and I've seen it never before. We read from left to right. The eye is not used to search in the right half of the screen.

Could you please send a new formatter that reverts only the chained method option?

Thx!

align

**Comment by paplorinc** [comment]
Done: https://github.com/javaslang/javaslang/pull/1520

**Pull request merged**
