### PR TITLE
Add test for Euler 14

### PR DESCRIPTION
**Pull request by patrox**
Example of how to use memoization and currying.

### CODE REVIEW

**Comment by danieldietrich** [comment]
How cool is that!? I love this collection API :-))

**Comment by ruslansennov** [comment]
:+1:

**Comment by danieldietrich** [comment]
A collegue of mine said we can start from `500_000L` instead of `1L`. I will test that later to reduce the time (currently 20sec on travis-ci).

**Comment by patrox** [comment]
yes, I'm aware that it takes some time to complete, for me it was around 6-7 seconds, but as for a test it was a bit slow - altough it's not a *unit test* per se. The most frustrating thing is that the corresponding Scala code completes below 1 sec ... I was wondering if we could make the Euler problems tests optional and run the remaining tests - these which actually test the core API.

**Comment by danieldietrich** [comment]
it's ok - it doesn't really matter. I like these high-level unit tests to test real-world application of our code. Scala has tail-recursion to execute tail-ended recursion in constant stack...

**Comment by patrox** [comment]
yes, similarily like in Clojure, as these languages support TCO (tail call optimization), which basically transforms tailrec calls in loops :)
BTW - I really miss Scala's @tailrec annotation :)

**Comment by danieldietrich** [comment]
Yes, @tailrec for Java would be really cool. Technically now it is possible said Brian Goetz but unfortunately it is not targetet to be implemented, yet...

**Pull request merged**
