### PR TITLE
Add codenvy developer workspace button to test this project inside Codenvy

### PR DESCRIPTION
**Pull request by benoitf**
### Codenvy Workspace Developer

Hello,

this pull request introduces a new ___“Codenvy workspace developer”___ button in the README of the project.

Contribute

This button enables anyone to test or contribute to the project without installing anything.

When a developer presses the button, a new workspace is created:

* A project runtime is created in a Docker container running in the Codenvy cloud (for free). You can customize this container using a Dockerfile.
* Source code is automatically cloned into the workspace as a “local” copy.
* A command set is added so users can build / run / debug the project with a single click.
* The project is automatically run so a new user can experience it hassle-free.
* A pull request panel in the IDE simplifies the process of creating a PR for new users. Experienced users can use the git menu in the IDE, or issue git commands from the built-in terminal.

This does not require ___any changes___ to the source code and has ___no cost___ to you or your users.

### CODE REVIEW

**Comment by danieldietrich** [comment]
Thank you. I like *possibilities*! Looking forward to check it out...

**Comment by danieldietrich** [comment]
Hi @benoitf,

I open the Developer Workspace. This repository contains a multi-module Maven project with additional source folders (src-gen). The src-gen folder does not seem to be recognized by the Codenvy. Is this a known issue?

**Comment by benoitf** [comment]
@danieldietrich I will give a look and keep you updated ! thanks for the feedback

**Comment by benoitf** [comment]
I confirmed the issue, I hope it will be fixed in the new version of the product. I will provide status here when it will be fixed

**Comment by danieldietrich** [comment]
Thank you!

**Pull request merged**
