### PR TITLE
HAMT performance

### PR DESCRIPTION
**Pull request by ruslansennov**

### CODE REVIEW

**Comment by danieldietrich** [comment]
Thank you! Did you profile it?

**Comment by ruslansennov** [comment]
> Did you profile it?

Yes :)
It was surprise for me that caching <code>Objects.hashCode(...)</code> can significantly increase performance. Also I removed <code>List</code> from <code>IndexedNode</code> because of very slow <code>List.get()</code> method.

**Comment by danieldietrich** [comment]
Great!!

**Comment by danieldietrich** [comment]
In theory, theory equals practice. Or as Lenin said "Trust but verify" (or something like this) :-))

**Pull request merged**
