### PR TITLE
map and flatMap

### LINKED ISSUE #488: Rethink flatMap et al.
The following is taken from a [pull request comment](https://github.com/javaslang/javaslang/pull/485#discussion_r37454043):

With `flatMap` we have a TODO in general but not here, with this pull-request.

Example:

```scala
scala> "123".flatMap(Some(_))
res0: String = 123

scala> "123".flatMap(c => Some(c + 0))
res1: scala.collection.immutable.IndexedSeq[Int] = Vector(49, 50, 51)

scala> val words = Set("Patryk", "Ruslan", "Daniel")
words: scala.collection.immutable.Set[String] = Set(Patryk, Ruslan, Daniel)

scala> words flatMap (word => word.toSet)
res2: scala.collection.immutable.Set[Char] = Set(e, s, n, y, t, u, a, i, l, P, r, R, k, D)

scala> words flatten (word => word.toSet)
res3: scala.collection.immutable.Set[Char] = Set(e, s, n, y, t, u, a, i, l, P, r, R, k, D)
```

Our flatMap works totally different. We need to check what is possible with Java, what makes sense and what is the expected behavior of flatMap. Maybe we need a Monad.unit(val) and Monoid.combine(m1, m2)...

### PR DESCRIPTION
**Pull request by danieldietrich**
Fixes #488

### CODE REVIEW

**Comment by danieldietrich** [comment]
Also renamed `(Hash)Map.merged()` to `merge()` and added `SortedMap`.

**Comment by danieldietrich** [comment]
Also fixes #501

**Comment by danieldietrich** [comment]
@patrox This will probably cause merge conflicts in HashMap ...
/cc @ruslansennov

**Comment by patrox** [comment]
@danieldietrich not a problem, altough I used them a bit differently:
```java
// TODO: please implement me
throw new UnsupportedOperationException("Not implemented yet!");
```

Because such comments are usually picked up by the IDE (in my case Idea), it's very easy to quicky find them all :)

**Comment by danieldietrich** [comment]
yes, that's nice. I will do that now

**Pull request merged**
