### PR TITLE
HashSet.containsKey() fixed

### PR DESCRIPTION
**Pull request by ruslansennov**

### CODE REVIEW

**Comment by danieldietrich** [comment]
You can't imagine how happy I am that we have a HashMap :-))

thumb-ub_fire

**Comment by ruslansennov** [comment]
wow... it was wrong subject :)

**Comment by danieldietrich** [comment]
I know what you meant :-)

**Comment by ruslansennov** [comment]
HashSet almost ready but I need some time

**Comment by danieldietrich** [comment]
No rush, I'm thankful for your hand! I will also add some functionality the next days - step by step.

**Pull request merged**
