### PR TITLE
Tuple to seq

### PR DESCRIPTION
**Pull request by ruslansennov**
I believe it will be useful (and it already useful in jackson module)

### CODE REVIEW

**Comment by danieldietrich** [comment]
Hi Ruslan,

we should find a general way to do it. I re-opened #692 and will work on it.

Please keep this PR open until we see in which direction #692 evolves.

Greets

Daniel

**Comment by danieldietrich** [comment]
I fiddled around for hours just to learn (again) that there is no good way to let extend Tuple the Iterable interface. Also inheriting other methods is overkill.

I committed an impl of the Tuple.toSeq method (which I regret now because of the merge conflicts). Could you please commit your tests for that method? I think the simplest way is to copy your tuples test of the Generator.scala to a fresh copy of master...

Thanks for your patience with me!

**Comment by ruslansennov** [comment]
done

**Comment by danieldietrich** [comment]
thx!!

**Pull request merged**
