### PR TITLE
Eulers 18, 67 solved

### PR DESCRIPTION
**Pull request by ruslansennov**

### CODE REVIEW

**Comment by danieldietrich** [comment]
Thx!
I've stared a while on `naive` and `smart` to see the difference :-)
It is only `memoized`, right?

**Comment by patrox** [comment]
BTW, I'm working on Euler 17 :)

**Comment by ruslansennov** [comment]
> It is only <code>memoized</code>, right?

exactly :smile: 
and with <code>ConcurrentHashMap</code> in <code>Memoized</code> implementation this trick doesn't work :cry:

**Comment by danieldietrich** [comment]
@patrox Ok!

**Comment by danieldietrich** [comment]
@ruslansennov that's really a weakness of ConcurrentHashMap. I wonder, if the creator(s) are aware of it...

**Pull request merged**
