### PR TITLE
Add tests for MatchError and $

### PR DESCRIPTION
**Pull request by patrox**
Some of these tests are quite simple, but they should bump the coverage a bit.

The next candidate is `Lazy`.

### CODE REVIEW

**Comment by danieldietrich** [comment]
Great, thx!

**Comment by patrox** [comment]
@danieldietrich please don't merge it yet - I'll be adding some tests soon, ok ?

**Comment by danieldietrich** [comment]
Ok, will go to sleep then and have a look tomorrow morning.

gdn8!

**Comment by patrox** [comment]
good night!

**Comment by patrox** [comment]
> 96.01%

@danieldietrich that will be all for this PR :)
The side-effect of writing these tests was that I finally grasped the basics of javaslang's pattern matching.

**Comment by danieldietrich** [comment]
great, thx :)

**Pull request merged**
