### PR TITLE
Deprecated API that will be removed in 3.0.0

### LINKED ISSUE #1893: Deprecate all API that will be removed in 3.0.0
For example

* Kind1, Kind2 will be removed
* Stack interface will be removed
* ...

See milestone 3.0.0 issues for a complete list.

### PR DESCRIPTION
**Pull request by danieldietrich**
Fixes #1893

### CODE REVIEW

**Comment by danieldietrich** [comment]
No code changed. Added only deprecation annotations and changed javadoc. Will merge now...

**Comment by ruslansennov** [comment]
@danieldietrich Why `FunctionN` is deprecated?
I found issue #1493 about `CheckedFunctionN` but not about `FunctionN`

**Comment by ruslansennov** [comment]
sorry, it is `SuppressWarnings` but not `Deprecated`...
I'm a little tired

**Comment by danieldietrich** [comment]
@ruslansennov yes - that's right. Sleep well, and thank you for all the improvements!!

**Pull request merged**
