### PR TITLE
Tuple prepend() & append()

### PR DESCRIPTION
**Pull request by ronanM**
New PR following reverted #1452.
See also #1505

### CODE REVIEW

**Comment by danieldietrich** [comment]
Hi @ronanM, thank you for the new PR. Mmhh, but I don't see the changes. This PR states 0 changed files. Am I missing s.th.?
Thanks for your help!

**Comment by ronanM** [comment]
I'm a bit confused, all my code disappear after merging master into `tuple-prepend-append` branch.

**Comment by danieldietrich** [comment]
Thanks - I'm also no git expert. ✨It's a kind of magic✨ :-)

**Comment by danieldietrich** [comment]
Thanks for bearing up with me. Nice change!

**Pull request merged**
