### PR TITLE
Improved coverage of Map implementations

### PR DESCRIPTION
**Pull request by AlparSzabados**
Improves: https://github.com/javaslang/javaslang/issues/1279

### CODE REVIEW

**Comment by paplorinc** [comment]
> Merging #1833 into master will increase coverage by 0.16%

Good job!

**Comment by danieldietrich** [comment]
Great! Many thanks :)

**Comment by ruslansennov** [comment]
>  could you please help us in identifying why these lines aren't covered?

Need more tests :)
Thank you, this evening I'll try to reach 100% in HAMT

**Comment by paplorinc** [comment]
Thanks @ruslansennov! :)
@danieldietrich, how can we achieve 98%? Would be awesome!
@AlparSzabados, you up for some more small wins like these? :)

**Comment by AlparSzabados** [comment]
@paplorinc sure! 98% would be nice and I think it's doable.

**Pull request merged**
