### PR TITLE
reduce*Option fixed #1021

### LINKED ISSUE #1021: When reduce* returns null reduce*Option must return Some(null) instead of None
The semantics of reduceLeftOption, reduceRightOption is to return None, if the underlying Value/Traversable is empty. If the operation successfully combines one or more elements, the result has to be Some.

### PR DESCRIPTION
**Pull request by ruslansennov**

### CODE REVIEW

**Comment by danieldietrich** [comment]
Right!

But... I have completely removed the methods reduceRightOption, reduceLeftOption from Traversable. They are now implemented as default in Value. There where also other unnecessary impls I think.

This PR can be closed. I urgently need to push my changes. They get more and more while refactoring this Monad stuff. Please wait until I've pushed them today...

**Comment by danieldietrich** [comment]
(I've also fixed that bug already)

**Comment by danieldietrich** [comment]
This is what I've done so far. Too much for one PR I think O_o
https://github.com/javaslang/javaslang/compare/master...danieldietrich:master

**Comment by ruslansennov** [comment]
> Too much for one PR I think O_o

yep, very bad PR :)

**Comment by danieldietrich** [comment]
I broke my new-years resolution to create local branches instead of working on my master. Needs to get better...

**Pull request closed without merging**
