### PR TITLE
Match tests added

### PR DESCRIPTION
**Pull request by ruslansennov**

### CODE REVIEW

**Comment by danieldietrich** [comment]
Seems the internet is down :) https://downdetector.com/status/google

**Comment by ruslansennov** [comment]
http://uncyclopedia.wikia.com/wiki/AAAAAAAAA!

**Comment by danieldietrich** [comment]
HAHAHAAAAAAA!

**Comment by danieldietrich** [comment]
restarted...

**Comment by danieldietrich** [comment]
Epic: first time two Javaslang PRs build simultaneously :)

**Pull request merged**
