### PR TITLE
Added Set.intersection(), difference() and union().

### PR DESCRIPTION
**Pull request by danieldietrich**
* Move hasDefiniteSize() and isTraversableAgain() from Traversable to TraversableOnce.
* Optimized HashSet.

@ruslansennov if this causes merge-problems because you're also on HashSet, I will wait with pulling this. Just give me a sign...

### CODE REVIEW

**Comment by danieldietrich** [comment]
@ruslansennov I think I will pull this (hoping you won't punch me for that :-) ) - the HashSet changes may be interesting, if you implement more methods...

**Comment by danieldietrich** [comment]
@ruslansennov Oohh - just realized I only touched Sets. This should not have produced merge-conflict impact to your HashMap changes...

**Comment by ruslansennov** [comment]
@danieldietrich no problem, all Sunday I was like a [sleepy kitty](http://bigbangtheory.wikia.com/wiki/Soft_Kitty) and didn't do anything :)

**Comment by danieldietrich** [comment]
@ruslansennov :-D

**Pull request merged**
