### PR TITLE
sliding(int,int) bug fixed

### PR DESCRIPTION
**Pull request by ruslansennov**
O_o

### CODE REVIEW

**Comment by danieldietrich** [comment]
Mmhh, I first had an intuitive solution, similar to yours, but changed it to the current because Scala REPL says:

```scala
scala> List(1, 2, 3, 4, 5).sliding(2).toList
res0: List[List[Int]] = List(List(1, 2), List(2, 3), List(3, 4), List(4, 5))

scala> List(1, 2, 3, 4).sliding(5, 3).toList
res1: List[List[Int]] = List(List(1, 2, 3, 4))
```

I don't think we have a bug here.

**Comment by ruslansennov** [comment]
O_o

**Comment by danieldietrich** [comment]
8-)

**Comment by ruslansennov** [comment]
But
```scala
scala> List(1, 2, 3, 4, 5).sliding(2, 4).toList
res0: List[List[Int]] = List(List(1, 2), List(5))
```
This should be investigated...

BTW, we HAVE a bug!
This code is completely wrong.
```java
        while (!list.isEmpty()) {
            final Tuple2<List<T>, List<T>> split = list.splitAt(size);
            result = result.prepend(split._1);
            list = split._2.isEmpty() ? Nil.instance() : list.drop(step);
        }
```
Should be something like this
```java
        while (list.length() >= size) {
            result = result.prepend(list.take(size));
            list = list.drop(step);
        }
```
or like this
```java
        while (list.length() >= size) {
            result = result.prepend(list.take(size));
            list = list.length() <= step ? empty() : list.drop(step);
        }
```

**Comment by danieldietrich** [comment]
Javaslang your first example right:

```java
List.of(1, 2, 3, 4, 5).sliding(2, 4); // = List(List(1, 2), List(5))
```

To prove the code wrong, we need a counter-example, i.e. an example where Scala's result is not equal to Javaslang's result.

```java
while (!list.isEmpty()) {

    // = Tuple2(take(size), drop(size))
    // splitAt is great here, because take and drop is calculated in one turn (e.g. for List)
    final Tuple2<List<T>, List<T>> split = list.splitAt(size);

    // essentially the same as result.prepend(list.take(size))
    result = result.prepend(split._1);

    // we need the drop(size) part (= split._2) for the case step < size.
    // because drop(size) = empty => we are finished. but drop(step) may not be empty.
    list = split._2.isEmpty() ? Nil.instance() : list.drop(step);

}
```

My tests led to similar results like Scala.

I know you have a good sense for code. What do you think is wrong exactly?

**Comment by ruslansennov** [comment]
It was an obsession, sorry :)

**Comment by danieldietrich** [comment]
obsession is good - keep it up and running :)

**Comment by danieldietrich** [comment]
Half the way there. Moved many static factory methods to Iterator. Collections may use these by delegating their static factory methods via `ofAll(() -> Iterator.xxx(...))`. TODOs added in `Iterator`. Currently the stuff is in my fork... Will be pulled soon into master.

**Pull request closed without merging**
