### PR TITLE
Add isMatch and isSome methods to Option

### PR DESCRIPTION
**Pull request by v1ctor**
I've added some useful methods at Option class. 
Correct me if there are such methods.

### CODE REVIEW

**Comment by danieldietrich** [comment]
We already have `exists(predicate)` for all Values (Option, Try, Traversable, ...). This is the same as `isMatch(predicate)`.

This `isSome` looks like an _imperative_ smell to me from the viewpoint of functional programming. What is the use-case?

Instead of

```java
result = opt.isSome(value) ? a : b;
```

it is better to

```java
result = opt.map(...).ifDefined(a, b);
```

Please convince me that isSome is needed :)

**Comment by danieldietrich** [comment]
@v1ctor I'm sure you have a use-case in mind or a code snippet. How would you use it in your application? Then I can see if we include it or express it with existing syntax.

**Comment by v1ctor** [comment]
I do something like that:
```java
void setValue(Object value) {
    if (!this.option.isSome(value)) {
         //Update value in DB
    }
    //Do nothing
}
```

**Comment by danieldietrich** [comment]
We will rename `boolean isSome(T element)` to `boolean contains(T element)` and pull the existing method from `Traversable` into `Value` (internal: `Iterable`).

I've done this with with #917. I hope you don't mind to close this PR. I'm very thankful for your great ideas! Keep on PR'ing!

**Comment by v1ctor** [comment]
Alright! It looks the same :)

**Comment by danieldietrich** [comment]
Thx!

**Pull request closed without merging**
