### PR TITLE
Gwt support

### PR DESCRIPTION
**Pull request by ruslansennov**
towards #1393 
* gwt profile removed
* all gwt stuff moved to javaslang module
* javaslang-gwt module contains only test and codeserver classes

### CODE REVIEW

**Comment by ruslansennov** [comment]
Travis knows nothing about google snapshots.
It seems we will wait for rc3

**Comment by danieldietrich** [comment]
Ok, thank you, we will wait then!

**Comment by ruslansennov** [comment]
@danieldietrich rc3 released, all tests passed

**Comment by danieldietrich** [comment]
@ruslansennov good news! We still have some time before releasing 2.1.0. We should wait for the final GWT 2.8.0 version.

**Comment by ruslansennov** [comment]
Can you pull this right now? To avoid GWT-incompatible commits in future

**Comment by danieldietrich** [comment]
yes, will do!

**Comment by danieldietrich** [comment]
> To avoid GWT-incompatible commits in future

How do we achieve this? Does the travis-ci build check GWT compatibility?

**Comment by ruslansennov** [comment]
See last build log :) Now gwt-tests executed on every building.

**Pull request merged**
