### PR TITLE
Adding matching on a range of values.

### PR DESCRIPTION
**Pull request by martincooper**
Hi Daniel,

I've implemented the matching which I raised an issue for the other day. I think this looks like a reasonable way to do it. 

```java
        final String result = Match
                .whenIn(new Integer[] { 1, 3, 5, 7 }, x -> "true")
                .whenIn(new Integer[] { 2, 4, 6, 8 }, x -> "false")
                .when(10, x -> "other")
                .apply(6);

        assertThat(result).isEqualTo("false");
```
The array creation inside the "whenIn" is a bit more verbose than I would have liked. It's a pity I can't use ```T... prototypes``` as the argument for the method as it's not the last argument.

Maybe something along the lines of this would be nice...

        final String result = Match
                .whenIn(1, 3, 5, 7).then(x -> "true")
                .whenIn(2, 4, 6, 8).then(x -> "false")
                .when(10).then(x -> "other")
                .apply(6);

Although this would most likely require a significant re-work.

Thanks

Martin

### CODE REVIEW

**Comment by danieldietrich** [comment]
Hi Martin,

this looks good! I like the `whenIn(...).then(...)` and `when(...).then(...)` syntax.

It seems you changed the generated `Match` class. Changes will be overwritten when re-generating sources, e.g. by calling `mvn clean generate-sources`. I'm currently also changing the `Match` generator (see #227) and about to merge it into master this evening (there will be a new `Match.of(...)` syntax that allows strong typed match expressions and monadic behavior like `map`, `flatMap`, `filter`).

If you don't mind, I will rework the `Match` generator according to your suggestion, because I'm already on it (see [Generator.scala](https://github.com/danieldietrich/javaslang/blob/17319a1123767d864562b190637a1d79f3d6ee2b/generator/Generator.scala#L39-L885)).

What do you think?

\- Daniel

**Comment by martincooper** [comment]
Hi Daniel

I didn't realise the Match class was generated :astonished:

Yep, it's cool for you to make these changes as you're already working on it. I look forward to testing it out after. :smiley:

Thanks!

**Comment by danieldietrich** [comment]
Thanks for making Match awesome! I will push a first version until tomorrow...

**Comment by danieldietrich** [comment]
> I will push a first version until tomorrow...

Need sleep :) Will go on tomorrow...

**Comment by danieldietrich** [comment]
The new syntax is now in place, details provided in #302.

**Pull request closed without merging**
