### PR TITLE
Traversable.flatMap() tests

### PR DESCRIPTION
**Pull request by ruslansennov**

### CODE REVIEW

**Comment by danieldietrich** [comment]
Great! Tomorrow evening (or Saturday morning) is the day... finally :)

**Comment by ruslansennov** [comment]
I don't believe

**Comment by danieldietrich** [comment]
Haha, it needs to. Need someone here to kick my ass to press the button on Friday.

**Comment by danieldietrich** [comment]
Can't believe that we go live. Must be thousands of hours of work! The project has grown up.

**Pull request merged**
