### PR TITLE
Unleashed javaslang.collection.Iterator. Refactored Collections.

### LINKED ISSUE #256: Re-organize collection.Tree
The current `Tree` type hierarchy is a little bit bulky.

As discussed [recently](https://github.com/javaslang/javaslang/issues/252), interfaces and implementations go hand-in-hand. Let me describe here, how we take the collection interfaces to the next level:

```java
            Traversable
                 |
               Tree
              /    \
     BinaryTree    ...
           /  \
RedBlackTree  ...
```

All trees in Javaslang are designed to have a value at each node. Also the empty tree exists for all tree interfaces.

```java
Tree<T> := Nil | Branch(T value, Seq<Tree> children)

BinaryTree<T> := Nil | Branch(BinaryTree<T> left, T value, BinaryTree<T> right)

// enum Color { RED, BLACK } handled internally
RedBlackTree<T> := Nil | Branch(RedBlackTree<T> left, T value, RedBlackTree<T> right)
```

`Tree` (_formerly: RoseTree_) is the most general tree data structure. It has

* a root
* (inner) nodes
* leaves
* an arbitrary amount of children

`BinaryTree` is an unbalanced binary search tree. Each node has at most two children: left and right. They are the simplest form of binary search trees. They perform poorly on ordered data and might take up to O(n) time.

`RedBlackTree` is a very efficient balanced binary search tree, maybe the fastest solution (with some tweaks) which exists so far. A color is internally used to keep the tree _aproximately_ balanced. Then no operation takes more than O(log n) time.

### LINKED ISSUE #291: Remove internal abstract classes from public API
E.g. the abstract collections which implement equals, hashCode and toString

### LINKED ISSUE #431: Implement Scala like Iterator with lazy map/flatMap capabilities
See [What is the difference between view, stream and iterator?](http://docs.scala-lang.org/tutorials/FAQ/stream-view-iterator.html).

There are use-cases within the collection library, e.g. HAMT and HashSet, where currently `Stream.ofAll(...).iterator()` is used to obtain a lazy Iterator.

Having a special `Iterator` is more lightweight compared to `Stream.iterator()`.

### PR DESCRIPTION
**Pull request by danieldietrich**
* Fixes #431 Implement Scala like Iterator with lazy map/flatMap capabilities
* Fixes #291 Remove internal abstract classes from public API
* Fixes #256 Re-organize collection.Tree
* Towards #433 Make complex hashCodes lazy  // but Deserialization of transient Lazy does not work!
* Towards #113 Make interface Tree extend Traversable
  * // it will at least extend Iterable and FilterMona, maybe TraversableOnce but not Traversable

### CODE REVIEW

**Comment by danieldietrich** [comment]
**@ruslansennov I'm on vacation with my family for one week, starting tomorrow. Notebook has to stay home o_O... I will try to go online at most once a day. We will see.**

**Comment by danieldietrich** [comment]
@ruslansennov I refactored the collections a little bit. Please have a look (HashSet, HashMap). There is now `javaslang.collection.Iterator`...

**Comment by ruslansennov** [comment]
Have a nice trip! It's a good idea to leave the laptop at home

**Comment by danieldietrich** [comment]
Yes...

**Comment by danieldietrich** [comment]
I made HAMT and Interface. That leaks the inner classes to the public.

**Pro:** this enables pattern matching by subtype, 'introspection' and Proxying of the HAMT.

**Con:** the public API shows more classes

I'm not sure. We can switch back, when in doubt. The RedBlackTree is also designed as Interface with inner static classes. I like interfaces in general. They are more flexible, and it seems a good design practice to me.

**Comment by ruslansennov** [comment]
> Con: the public API shows more classes

This was the reason I chose <code>abstract class</code> instead of <code>interface</code>
But there is not problem, I believe it's just a matter of taste

**Comment by danieldietrich** [comment]
Ok. Abstract classes were always some intermediate types to me, not intended to be directly used other than extending them for own types. We will go with interfaces for now. I hope that Java 9 gives us some extra syntax regarding interfaces to hide private methods and maybe private inner classes. We will see.

**Pull request merged**
