### PR TITLE
Traversable.sum() performance

### PR DESCRIPTION
**Pull request by ruslansennov**
```java
@Test
public void kekeke() {
    System.out.println(Stream.range(0, 10000000).sum());
}
```
Time of computations decreases from **13.2 sec** to **8.2 sec** on my computer

### CODE REVIEW

**Comment by danieldietrich** [comment]
Incredible!

**Comment by ruslansennov** [comment]
trust me

**Comment by danieldietrich** [comment]
I do

**Comment by danieldietrich** [comment]
travis-ci currently does not seem to work. I've also restarted another build to deploy the new io.javaslang snapshot artifacts... zzZzz

**Pull request merged**
