### PR TITLE
Remove "throws Throwable" clause from partial application in CheckedFunction

### LINKED ISSUE #1257: Throwable in signature for partial application of CheckedFunctions
I do not really understand why the signature of methods for partial application of CheckedFunctions expects a Throwable, e.g.:

```java
default CheckedFunction1<T2, R> apply(T1 t1) throws Throwable {
    return (T2 t2) -> apply(t1, t2);
}
```

Partial application of checked functions become very unhandy under this circumstances and from my point of view it's unncessary to expect a Throwable at this point. But I think you see a sense behind this signature :-) so I would like to know the reason your design decision ;-)

### PR DESCRIPTION
**Pull request by pivovarit**
This closes #1257

### CODE REVIEW

**Comment by ruslansennov** [comment]
Hi Grzegorz 
You should edit <code>Generator</code> but not <code>src-gen/*</code> classes

**Comment by pivovarit** [comment]
Oh, sh*t. I'm on it

**Comment by pivovarit** [comment]
@ruslansennov I updated my commit

**Comment by ruslansennov** [comment]
Sorry, I was not accurate in my comment :)
You should 
1. manually change only Generator
2. run <code>mvn test</code> (then all <code>src-gen/</code> files will be changed automatically)
3. all changes push to GitHub

**Comment by pivovarit** [comment]
So you expect me to push both Generator.scala and updated generated files?

**Comment by ruslansennov** [comment]
Yes!

**Comment by pivovarit** [comment]
What's the point of keeping track of the generator and stuff it generates during compilation?

**Comment by ruslansennov** [comment]
> What's the point of keeping track of the generator and stuff it generates during compilation?

Both points of view (include/exclude generated files) makes sense. I prefer exclude it from my projects,  It seems Daniel has another opinion :smile:

**Comment by pivovarit** [comment]
I prefer this approach too. Anyway, I updated my commit

**Comment by ruslansennov** [comment]
Thank you
Now we are waiting for Daniel

**Comment by talios** [comment]
One good thing of including generated code in version control (IMHO) comes during code review, being able to see what code is being generated is often handy, and may often change the opinion of the code review.  i.e. your change may _look_ small - but it might have far further reaching impact than you, or an unfamiliar reviewer may expect.

That being said, care should be taken to generate the code as far away from "real code" as possible - and _never_ in the same directory :)

**Comment by pivovarit** [comment]
@talios well, what if commiter is true evil and commits fake generated files? ;)

**Comment by danieldietrich** [comment]
@pivovarit good point! I will open an issue to enhance the ci-build to detect evil commits of generated sources.

It is as @talios said - I want to see the changes in code reviews. And I want to browse the actual code online :-)

**Comment by danieldietrich** [comment]
LGTM! Thx

**Pull request merged**
