### PR TITLE
renamed gen + repeat methods to iterate and continually in Iterator and Stream

### PR DESCRIPTION
**Pull request by mvh77**
to match the Scala API

### CODE REVIEW

**Comment by mvh77** [comment]
Btw I have a problem with IntelliJ giving me:
....../javaslang/javaslang/target/generated-sources/annotations/javaslang/Patterns.java
Error:(10, 14) java: duplicate class: javaslang.Patterns

I couldn't run test cases in IntelliJ, had to do it on the command line, really annoying. Is this a known issue?

**Comment by ruslansennov** [comment]
I had same problem. Solved with two steps: maven build and then syncing Idea

**Comment by danieldietrich** [comment]
Great, thanks!!

> I couldn't run test cases in IntelliJ, had to do it on the command line, really annoying. Is this a known issue?

Yep, fixed on my local branch. IntelliJ does not recognize the compiler option for generated sources directory specified in the maven-compiler-plugin. I think it is an IntelliJ bug - the compiler args should be passed to IntelliJ.

However, I fixed it by using the default compiler args for annotation processing. Will commit that.

**Comment by danieldietrich** [comment]
Top!

**Comment by danieldietrich** [comment]
@mvh77 @ruslansennov the IntelliJ problem should be fixed in some minutes with #1149

**Pull request merged**
