### PR TITLE
HAMT.size() improved #578

### PR DESCRIPTION
**Pull request by ruslansennov**
something like this

### CODE REVIEW

**Comment by danieldietrich** [comment]
Thank you, Ruslan, LGTM!

**Comment by ruslansennov** [comment]
what happened with travis?

**Comment by danieldietrich** [comment]
Mmhh, sometimes the cloud has no more capacity. I think it will start in a few minutes...

**Comment by danieldietrich** [comment]
Seems to be stuck. I will merge now. Then a new build is started.

**Comment by danieldietrich** [comment]
Travis is still not operational. Does not matter, if local builds are working via `mvn clean test`.

**Pull request merged**
