### PR TITLE
Fixes unexpected list behavior

### LINKED ISSUE #298: Unexpected List.map behavior for independent values
@ggalmazor Gave an example, where a List seems to be in the wrong order after mapping values:

https://gist.github.com/ggalmazor/c122cc15ae971dbd08b8

Also other List operations should be checked regarding the use of `foldLeft` and `foldRight`.

This fix will change the behavior of List operations for some special cases.

### PR DESCRIPTION
**Pull request by danieldietrich**
Fixes #298

### CODE REVIEW

**Comment by ggalmazor** [comment]
I see that this fix is not available yet in 2.0.0-beta version... Is this right?

**Comment by danieldietrich** [comment]
It should be all fine.

Here is 2.0.0-beta: https://github.com/javaslang/javaslang/blob/javaslang-2.0.0-beta/src/main/java/javaslang/collection/List.java#L594

and RC1: https://github.com/javaslang/javaslang/blob/master/src/main/java/javaslang/collection/List.java#L593

Do we have a regression? Do you have an example?

Thx!

**Comment by ggalmazor** [comment]
Sorry! My local maven cache was giving me a hard time and I was seeing 1.2.2 as 2.0.0...

**Comment by danieldietrich** [comment]
Thx for the info - then I expect it to work (it should because of the unit tests).

**Pull request merged**
